### ISSUE TITLE
Compile error: could not stream priv/tmp_downloads/300363//backward: no such file or directory

### ISSUE THREAD

**Issue by Timrael** [lau/tzdata#13]
Hi, I have an error on compilation on CentOS 6.3 with tzdata 0.5.2:

Could you please tell me how to solve it?

```
Generated ecto app



20:54:13.422 [error] Task #PID<0.1047.0> started from :tzdata_release_updater terminating
** (File.Error) could not stream priv/tmp_downloads/300363//backward: no such file or directory
    (elixir) lib/file/stream.ex:77: anonymous fn/2 in Enumerable.File.Stream.reduce/3
    (elixir) lib/stream.ex:1077: anonymous fn/5 in Stream.resource/3
    (elixir) lib/stream.ex:1240: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:1391: Enum.reduce/3
    (elixir) lib/enum.ex:2130: Enum.to_list/1
    (tzdata) lib/tzdata/parser.ex:16: Tzdata.Parser.process_file/1
    (tzdata) lib/tzdata/basic_data_map.ex:8: anonymous fn/2 in Tzdata.BasicDataMap.from_files_in_dir/1
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
Function: #Function<1.108323131/0 in Tzdata.ReleaseUpdater.init/1>
    Args: []



==> cowlib (compile)
```

**Comment by lau** [comment]
Please upgrade to version 0.5.4 and see if that fixes the problem.
