### ISSUE TITLE
timezone :tz_release_updater terminating

### ISSUE THREAD

**Issue by alpeshjamgade** [lau/tzdata#151]
can anyone help me on this, since last few days facing this issue in production. 
everything in build is the same including library version. suddenly getting this issue.

:tzdata, "~> 1.0"
elixir 1.11.2
erlang 23.0

Error: 

10:31:56.726 [error]  GenServer :tzdata_release_updater terminating
** (ArgumentError) argument error
    :erlang.element(1, :error)
    (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Last message: :check_if_time_to_update
State: []

**Comment by peaceful-james** [comment]
Can you upgrade to latest version (1.2).

https://github.com/lau/tzdata/commit/ba42b763610f3ce890f4e00f58b9b969d7a3d5c6

![image](https://github.com/user-attachments/assets/dc5a0b55-1880-4a33-9ca6-c93ec7951be4)

From your stacktrace:

```
:erlang.element(1, :error)
```

You can see the commit I linked and screenshotted changes a line to return a tuple instead of an int. I think this is at the heart of your issue.

**Comment by fortmarek** [comment]
Thanks @peaceful-james!

We were seeing the same issue and upgrading `tzdata` resolved it for us.
