### ISSUE TITLE
tzdata_release_updater terminating

### ISSUE THREAD

**Issue by sjoconnor** [lau/tzdata#45]
Hello, I have a Phoenix application that I am running inside a Docker container ([bitwalker/alpine-erlang:20.0](https://hub.docker.com/r/bitwalker/alpine-erlang/)). I'm using [mix_docker](https://github.com/Recruitee/mix_docker) for releases. 

When I run my application locallyI don't receive this error, but when I run it inside my container this error happens every few seconds or so. I can't find anywhere in my application where I'm using `tzdata`. I'm having a hard time tracking down what's causing this error. Any help you could provide would be much appreciated.

### Error

```elixir
22:23:52.554 [error] GenServer :tzdata_release_updater terminating
** (File.Error) could not write to file "/opt/app/lib/tzdata-0.5.12/priv/tmp_downloads/335571_44358462/latest.tar.gz": no such file or directory
    (elixir) lib/file.ex:831: File.write!/3
    (tzdata) lib/tzdata/data_loader.ex:17: Tzdata.DataLoader.download_new/1
    (tzdata) lib/tzdata/data_builder.ex:9: Tzdata.DataBuilder.load_and_save_table/0
    (tzdata) lib/tzdata/release_updater.ex:41: Tzdata.ReleaseUpdater.poll_for_update/0
    (tzdata) lib/tzdata/release_updater.ex:17: Tzdata.ReleaseUpdater.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :check_if_time_to_update

=CRASH REPORT==== 2-Nov-2017::22:23:52 ===
  crasher:
    initial call: Elixir.Tzdata.ReleaseUpdater:init/1
    pid: <0.2586.0>
    registered_name: tzdata_release_updater
    exception error: #{'__exception__' => true,
                       '__struct__' => 'Elixir.File.Error',
                       action => <<"write to file">>,
                       path =>
                           <<"/opt/app/lib/tzdata-0.5.12/priv/tmp_downloads/335571_44358462/latest.tar.gz">>,
                       reason => enoent}
      in function  'Elixir.File':'write!'/3 (lib/file.ex, line 831)
      in call from 'Elixir.Tzdata.DataLoader':download_new/1 (lib/tzdata/data_loader.ex, line 17)
      in call from 'Elixir.Tzdata.DataBuilder':load_and_save_table/0 (lib/tzdata/data_builder.ex, line 9)
      in call from 'Elixir.Tzdata.ReleaseUpdater':poll_for_update/0 (lib/tzdata/release_updater.ex, line 41)
      in call from 'Elixir.Tzdata.ReleaseUpdater':handle_info/2 (lib/tzdata/release_updater.ex, line 17)
      in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 686)
    ancestors: [<0.1411.0>,<0.1410.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1411.0>]
    dictionary: [{random_seed,{27839,21123,25074}}]
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 18757
  neighbours:

=SUPERVISOR REPORT==== 2-Nov-2017::22:23:52 ===
     Supervisor: {<0.1411.0>,'Elixir.Supervisor.Default'}
     Context:    child_terminated
     Reason:     {#{'__exception__' => true,
                    '__struct__' => 'Elixir.File.Error',
                    action => <<"write to file">>,
                    path =>
                        <<"/opt/app/lib/tzdata-0.5.12/priv/tmp_downloads/335571_44358462/latest.tar.gz">>,
                    reason => enoent},
                  [{'Elixir.File','write!',3,
                       [{file,"lib/file.ex"},{line,831}]},
                   {'Elixir.Tzdata.DataLoader',download_new,1,
                       [{file,"lib/tzdata/data_loader.ex"},{line,17}]},
                   {'Elixir.Tzdata.DataBuilder',load_and_save_table,0,
                       [{file,"lib/tzdata/data_builder.ex"},{line,9}]},
                   {'Elixir.Tzdata.ReleaseUpdater',poll_for_update,0,
                       [{file,"lib/tzdata/release_updater.ex"},{line,41}]},
                   {'Elixir.Tzdata.ReleaseUpdater',handle_info,2,
                       [{file,"lib/tzdata/release_updater.ex"},{line,17}]},
                   {gen_server,try_dispatch,4,
                       [{file,"gen_server.erl"},{line,616}]},
                   {gen_server,handle_msg,6,
                       [{file,"gen_server.erl"},{line,686}]},
                   {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.2586.0>},
                  {id,'Elixir.Tzdata.ReleaseUpdater'},
                  {mfargs,{'Elixir.Tzdata.ReleaseUpdater',start_link,[]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]
```

### Dependencies 

`mix.exs`

```elixir
  defp deps do
    [
      {:phoenix, "~> 1.3.0"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      # {:mariaex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.10"},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:httpoison, "~> 0.13"},
      {:poison, "~> 3.1"},
      {:mix_docker, "~> 0.5.0"},

      # Dev or test deps
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:hound, "~> 1.0", only: [:integration, :dev]},
      {:bypass, "~> 0.8", only: [:integration, :dev]},
      {:mox, "~> 0.2.0", only: [:test, :dev]},
    ]
  end
```

**Comment by sjoconnor** [comment]
I went ahead and added `config :tzdata, :data_dir, "./<some_directory>"` to my `config.exs` file which seems to have fixed the issue.
