### ISSUE TITLE
DateTime.now with invalid time zone crashes

### ISSUE THREAD

**Issue by wojtekmach** [lau/tzdata#72]
I'm using Elixir master and tzdata master.

```
iex> DateTime.now("America/New_Yor", Tzdata.TimeZoneDatabase)
** (MatchError) no match of right hand side value: {:error, :not_found}
    (tzdata) lib/tzdata.ex:168: Tzdata.periods_for_time/3
    (tzdata) lib/tzdata/time_zone_database.ex:15: Tzdata.TimeZoneDatabase.time_zone_period_from_utc_iso_days/2
    (elixir) lib/calendar/datetime.ex:443: DateTime.shift_zone_for_iso_days_utc/5
```

Per `DateTime.now` docs, it should return `{:error, :time_zone_not_found}` instead.

**Comment by lau** [comment]
Thank you. It should work in master now. The Tzdata.TimeZoneDatabase functionality needs some testing which I'll add soon.
