### ISSUE TITLE
GenServer :tzdata_release_updater terminating

### ISSUE THREAD

**Issue by schnittchen** [lau/tzdata#81]
```
20:21:02.252 [error] GenServer :tzdata_release_updater terminating
** (FunctionClauseError) no function clause matching in Tzdata.Util.first_matching_weekday_in_month/4
    (tzdata) lib/tzdata/util.ex:73: Tzdata.Util.first_matching_weekday_in_month(1932, 4, 7, [])
    (tzdata) lib/tzdata/util.ex:329: Tzdata.Util.time_for_rule/2
    (tzdata) lib/tzdata/period_builder.ex:161: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
Last message: :check_if_time_to_update
```

This might just be a weird blip on AWS. Is anyone seeing this on other infrastructure as well?

**Comment by lau** [comment]
What version of Tzdata are you using?

**Comment by schnittchen** [comment]
D'uh, forgot to mention the obvious! I'm a bit behind on `0.5.20`.

Since I'm seeing this today for the first time, master could be affected as well.

I'm sure somebody will comment here if that is the case.

**Comment by lau** [comment]
It looks like it is not just you. The new version of the tzdata (2019b) broke the Tzdata implementation: It has an entry for "Apr	Sun>=25" - a Sunday in April on the 25th or later. But in 1932 there was no Sunday on or after the 25th of April was in April. The first Sunday after that was on May 1st. I will release a fix.

**Comment by lau** [comment]
New releases are out with a fix:

- 1.0.1 if you are using Elixir 1.8+
- 0.5.21 for older versions of Elixir

**Comment by schnittchen** [comment]
Thank you @lau for your awesome work!

**Comment by lpil** [comment]
Thank you! <3

**Comment by lau** [comment]
@schnittchen You're welcome. Thank you for reporting the issue.

**Comment by INGCRENGIFO** [comment]
@lau Thank you!!!!!!!!!
```
0.5.21 for older versions of Elixir
```
