### ISSUE TITLE
UndefinedFunctionError or wrong gap when date-time hits exactly the start of a gap

### ISSUE THREAD

**Issue by NickNeck** [lau/tzdata#90]
Hello, if the date-time hits exactly the start of a gap the following values are returned:
```elixir
iex(11)> Tzdata.TimeZoneDatabase.time_zone_periods_from_wall_datetime(~N[2019-03-10 02:00:00], "America/Goose_Bay")
{:gap,
 {%{
    from_wall: ~N[2018-03-11 03:00:00],
    std_offset: 3600,
    until_wall: ~N[2018-11-04 02:00:00],
    utc_offset: -14400,
    zone_abbr: "ADT"
  }, ~N[2018-11-04 02:00:00]},
 {%{
    from_wall: ~N[2019-03-10 03:00:00],
    std_offset: 3600,
    until_wall: ~N[2019-11-03 02:00:00],
    utc_offset: -14400,
    zone_abbr: "ADT"
  }, ~N[2019-03-10 03:00:00]}}
iex(12)> Tzdata.TimeZoneDatabase.time_zone_periods_from_wall_datetime(~N[1884-01-01 00:00:00], "America/Goose_Bay")
** (UndefinedFunctionError) function nil.utc_off/0 is undefined. If you are using the dot syntax, such as map.field or module.function, make sure the left side of the dot is an atom or a map
    nil.utc_off()
    (tzdata) lib/tzdata/time_zone_database.ex:97: Tzdata.TimeZoneDatabase.old_tz_period_to_new/1
    (tzdata) lib/tzdata/time_zone_database.ex:67: Tzdata.TimeZoneDatabase.gap_for_time_zone/2
iex(12)>
```
One second later everything is ok:
```elixir
iex(14)> Tzdata.TimeZoneDatabase.time_zone_periods_from_wall_datetime(~N[2019-03-10 02:00:01], "America/Goose_Bay")
{:gap,
 {%{
    from_wall: ~N[2018-11-04 01:00:00],
    std_offset: 0,
    until_wall: ~N[2019-03-10 02:00:00],
    utc_offset: -14400,
    zone_abbr: "AST"
  }, ~N[2019-03-10 02:00:00]},
 {%{
    from_wall: ~N[2019-03-10 03:00:00],
    std_offset: 3600,
    until_wall: ~N[2019-11-03 02:00:00],
    utc_offset: -14400,
    zone_abbr: "ADT"
  }, ~N[2019-03-10 03:00:00]}}
iex(15)> Tzdata.TimeZoneDatabase.time_zone_periods_from_wall_datetime(~N[1884-01-01 00:00:01], "America/Goose_Bay")
{:gap,
 {%{
    from_wall: :min,
    std_offset: 0,
    until_wall: ~N[1884-01-01 00:00:00],
    utc_offset: -14500,
    zone_abbr: "LMT"
  }, ~N[1884-01-01 00:00:00]},
 {%{
    from_wall: ~N[1884-01-01 00:30:48],
    std_offset: 0,
    until_wall: ~N[1918-01-01 00:00:00],
    utc_offset: -12652,
    zone_abbr: "NST"
  }, ~N[1884-01-01 00:30:48]}}
iex(16)>
```
```elixir
iex(1)> Tzdata.tzdata_version
"2019c"
```
```
$> mix hex.outdated tzdata
Current version 1.0.2 of dependency is up to date!
```

**Comment by lau** [comment]
Thanks for the report. I believe this is fixed by https://github.com/lau/tzdata/pull/111 In version 1.0.5 it should work.
